########################################################################
# Makefile for qsort
#
########################################################################

CC         =  mpicc
CCFLAGS    =  -O3
LIBS       =  -lmpi

qsort:          qsort.c
	$(CC) $(CCFLAGS) -o qsort qsort.c $(LIBS)